[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"  # Apply to all paths
  [headers.values]
    Access-Control-Allow-Origin = "*" # Allow all origins

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 